import { useState, useEffect } from 'react'
import { useAccount, useConnect, useWriteContract, usePublicClient, useSwitchChain, useReconnect } from 'wagmi'
import { parseAbi, getAddress, parseEther } from 'viem'
import confetti from 'canvas-confetti'
import { Sparkles, Copy, Check, RotateCcw, Wallet, History, AlertCircle, Coins, Download, Sun, Moon, ChevronDown, HelpCircle } from 'lucide-react'

const ERC20_ABI = parseAbi([
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 value) returns (bool)'
])

const PAYMENT_ABI = parseAbi([
  'function payAndGenerate(string calldata requestId) external',
  'function feeAmount() view returns (uint256)'
])

interface SavedGeneration {
  prompt: string
  tone: string
  caption: string
  hashtags: string[]
  imageUrl?: string
  timestamp: number
}

const TONES = [
  { name: 'Hype 🔥', value: 'Hype' },
  { name: 'Aesthetic ✨', value: 'Aesthetic' },
  { name: 'Funny 💀', value: 'Funny' },
  { name: 'Professional 💼', value: 'Professional' },
  { name: 'Savage 😈', value: 'Savage' }
]

const FAQ_DATA = [
  {
    question: "What is an AI caption generator?",
    answer: "An AI caption generator is an online tool that uses advanced natural language processing (NLP) algorithms to instantly write engaging captions, hashtags, and social media post copy based on a brief topic, keyword, or prompt."
  },
  {
    question: "How do I write social media captions using AI?",
    answer: "Simply input your post topic or main idea, select a tone (such as Aesthetic, Hype, Funny, Professional, or Savage), and generate. You can copy the generated text and download corresponding high-quality marketing images generated by models like FLUX-Schnell."
  },
  {
    question: "Do AI-generated captions improve SEO and reach?",
    answer: "Yes! High-quality AI captions loaded with target keywords and highly relevant hashtags help social media search engines index your post, expanding your organic reach, discoverability, and audience engagement."
  },
  {
    question: "Is CaptionAI free to use?",
    answer: "CaptionAI runs on a transparent, pay-per-use model. Instead of recurring monthly subscriptions, you pay a microfee of only 0.02 cUSD (approx. ₹1.60 INR) per generation directly using your connected Celo Sepolia web3 wallet."
  },
  {
    question: "How does web3 payment work for caption generation?",
    answer: "When you generate a post, the app connects to your crypto wallet (like MiniPay, MetaMask, or Rabby) on the Celo network and securely approves a microtransaction of 0.02 cUSD. This pays for the exact server-side LLM and image model computation you consume, with no commitments or hidden fees."
  }
]

export default function App() {
  const { address, isConnected, chain } = useAccount()
  const { connect, connectors, error: connectError, isPending: isConnecting } = useConnect()
  const publicClient = usePublicClient()
  const { writeContractAsync } = useWriteContract()
  const { switchChain, switchChainAsync } = useSwitchChain()
  const { reconnect } = useReconnect()

  // Set connect errors in app state
  useEffect(() => {
    if (connectError) {
      setErrorMsg(connectError.message || 'Failed to connect wallet')
    }
  }, [connectError])

  const TARGET_CHAIN_ID = 11142220 // Celo Sepolia (Testnet)

  // App States
  const [prompt, setPrompt] = useState('')
  const [selectedTone, setSelectedTone] = useState('Hype')
  const [loadingStep, setLoadingStep] = useState<string | null>(null)
  const [errorMsg, setErrorMsg] = useState<string | null>(null)
  
  // Results
  const [result, setResult] = useState<{ caption: string; hashtags: string[]; imageUrl?: string } | null>(null)
  const [copied, setCopied] = useState(false)
  const [history, setHistory] = useState<SavedGeneration[]>([])
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'dark')

  useEffect(() => {
    if (theme === 'light') {
      document.documentElement.classList.add('light')
    } else {
      document.documentElement.classList.remove('light')
    }
    localStorage.setItem('theme', theme)
  }, [theme])

  // Network contract configuration
  const isMainnet = chain?.id === 42220
  
  // Official Mento stablecoin (cUSD / USDm) addresses
  const CUSD_ADDRESS = isMainnet
    ? '0x765de816845861e75a25fca122bb6898b8b1282a'
    : '0xdE9e4C3ce781b4bA68120d6261cbad65ce0aB00b' // Sepolia (USDm)

  // Deployed contract address (can load from Vite env, fallback will be updated after deployment)
  const PAYMENT_CONTRACT_ADDRESS = (import.meta.env.VITE_CONTRACT_ADDRESS || 
    (isMainnet
      ? '0x0000000000000000000000000000000000000000' // We will deploy on Celo Mainnet
      : '0x2C5334DDEaFfc6A56554401EcabD56b0E75Cf3B2')) as `0x${string}` // Deployed Sepolia address

  const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001'

  // MiniPay Detection
  const isMiniPay = typeof window !== 'undefined' && (window as any).ethereum?.isMiniPay

  const [hasAttemptedAutoConnect, setHasAttemptedAutoConnect] = useState(false)

  // 1. Silent Auto-reconnect for returning users & auto-connect specifically for MiniPay
  useEffect(() => {
    reconnect()
  }, [reconnect])

  useEffect(() => {
    if (isMiniPay && !isConnected && !isConnecting && !hasAttemptedAutoConnect) {
      const injectedConnector = connectors.find((c) => c.id === 'injected' || c.name.toLowerCase().includes('injected'))
      if (injectedConnector) {
        setHasAttemptedAutoConnect(true)
        connect({ connector: injectedConnector })
      }
    }
  }, [isMiniPay, isConnected, connectors, connect, isConnecting, hasAttemptedAutoConnect])

  // 2. Load History
  useEffect(() => {
    const cached = localStorage.getItem('caption_ai_history')
    if (cached) {
      try {
        setHistory(JSON.parse(cached))
      } catch (e) {
        console.error(e)
      }
    }
  }, [])

  const saveToHistory = (newGen: SavedGeneration) => {
    const updated = [newGen, ...history.slice(0, 4)]
    setHistory(updated)
    localStorage.setItem('caption_ai_history', JSON.stringify(updated))
  }

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // 3. Execution Flow
  const handleGenerate = async () => {
    if (!prompt.trim()) return
    setErrorMsg(null)
    setLoadingStep('Verifying balance and allowance...')

    try {
      if (!address || !publicClient) {
        throw new Error('Wallet not connected or network unavailable')
      }

      // Ensure the wallet is on the correct network (Celo Sepolia)
      if (chain?.id !== TARGET_CHAIN_ID) {
        setLoadingStep('Switching network to Celo Sepolia...')
        try {
          await switchChainAsync({ chainId: TARGET_CHAIN_ID })
        } catch (switchError) {
          throw new Error('Please switch your wallet network to Celo Sepolia to proceed.')
        }
        // Wait a brief moment for chain change to propagate
        await new Promise((resolve) => setTimeout(resolve, 1500))
      }

      const userAddress = getAddress(address)
      const spenderAddress = getAddress(PAYMENT_CONTRACT_ADDRESS)
      const cUSDTokenAddress = getAddress(CUSD_ADDRESS)

      // Check cUSD allowance
      const currentAllowance = await publicClient.readContract({
        address: cUSDTokenAddress,
        abi: ERC20_ABI,
        functionName: 'allowance',
        args: [userAddress, spenderAddress]
      })

      const feeAmount = parseEther('0.02') // 0.02 cUSD
      const approvalAmount = parseEther('0.50') // 0.50 cUSD to optimize future runs

      // If allowance is insufficient, request approval
      if (currentAllowance < feeAmount) {
        setLoadingStep('Approving cUSD (0.50 cUSD for 25 runs)...')
        const approveTx = await writeContractAsync({
          address: cUSDTokenAddress,
          abi: ERC20_ABI,
          functionName: 'approve',
          args: [spenderAddress, approvalAmount]
        })
        
        setLoadingStep('Waiting for approval receipt...')
        await publicClient.waitForTransactionReceipt({ hash: approveTx, confirmations: 0 })
      }

      // Execute payment contract call
      setLoadingStep('Paying fee (0.02 cUSD)...')
      const requestId = Math.random().toString(36).substring(7) + Date.now()
      
      const payTx = await writeContractAsync({
        address: spenderAddress,
        abi: PAYMENT_ABI,
        functionName: 'payAndGenerate',
        args: [requestId]
      })

      setLoadingStep('Waiting for on-chain receipt...')
      const receipt = await publicClient.waitForTransactionReceipt({ hash: payTx, confirmations: 0 })

      if (receipt.status !== 'success') {
        throw new Error('On-chain payment transaction failed')
      }

      // Call backend API to verify and generate caption
      setLoadingStep('Verifying receipt & generating caption...')
      const response = await fetch(`${API_BASE_URL}/api/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          walletAddress: address,
          txHash: receipt.transactionHash,
          prompt: prompt,
          tone: selectedTone
        })
      })

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || `Verification failed with status: ${response.status}`)
      }

      const data = await response.json()
      setResult(data)
      
      // Save to local cache history
      saveToHistory({
        prompt: prompt,
        tone: selectedTone,
        caption: data.caption,
        hashtags: data.hashtags,
        imageUrl: data.imageUrl,
        timestamp: Date.now()
      })

      // Celebration!
      confetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.8 },
        colors: ['#6c63ff', '#ff6584', '#4ade80']
      })

    } catch (e: any) {
      console.error(e)
      setErrorMsg(e.message || 'An unexpected error occurred during generation.')
    } finally {
      setLoadingStep(null)
    }
  }

  const resetGenerator = () => {
    setPrompt('')
    setResult(null)
    setErrorMsg(null)
  }

  const getLoadingSteps = (currentStep: string) => {
    const steps = [
      {
        id: 'wallet',
        label: 'Wallet & Network Status',
        desc: 'Verifying connection and switching to Celo Sepolia',
        status: 'pending'
      },
      {
        id: 'payment',
        label: 'cUSD Micro-Payment',
        desc: 'Approving fee and submitting secure transaction',
        status: 'pending'
      },
      {
        id: 'generation',
        label: 'AI Content Generation',
        desc: 'Executing Gemini & HF FLUX models in parallel',
        status: 'pending'
      }
    ]

    if (!currentStep) return steps

    // Step 1: Wallet & Network
    if (currentStep.includes('Verifying') || currentStep.includes('Switching')) {
      steps[0].status = 'active'
    } else {
      steps[0].status = 'complete'
    }

    // Step 2: Payment
    if (
      currentStep.includes('Approving') ||
      currentStep.includes('receipt') ||
      currentStep.includes('Paying') ||
      currentStep.includes('on-chain')
    ) {
      steps[0].status = 'complete'
      steps[1].status = 'active'
    } else if (currentStep.includes('generating') || currentStep.includes('Verifying receipt')) {
      steps[0].status = 'complete'
      steps[1].status = 'complete'
      steps[2].status = 'active'
    }

    return steps
  }

  return (
    <div className="min-h-screen w-full bg-[var(--bg-base)] text-[var(--text-primary)] relative overflow-x-hidden bg-mesh bg-dots flex flex-col justify-between">
      
      {/* Glow Orbs */}
      <div className="glow-orb glow-orb-purple w-[500px] h-[500px] -top-[150px] -left-[100px]" aria-hidden="true" />
      <div className="glow-orb glow-orb-pink w-[400px] h-[400px] -bottom-[100px] -right-[100px]" aria-hidden="true" />

      {/* Glassmorphic Header */}
      <header className="sticky top-0 z-50 bg-[var(--bg-surface)]/85 backdrop-blur-md border-b border-[var(--border-subtle)]">
        <div className="max-w-6xl w-full mx-auto px-4 md:px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <img
              src="/favicon.svg"
              alt="CaptionAI Logo"
              className="w-10 h-10 object-contain transition-transform duration-300 hover:scale-105"
            />
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-bold tracking-tight text-[var(--text-primary)] leading-tight">CaptionAI</h1>
                {isMiniPay && (
                  <span className="text-[9px] font-extrabold bg-[#4ade80]/15 text-[#4ade80] px-2 py-0.5 rounded border border-[#4ade80]/20 uppercase tracking-widest">
                    MiniPay
                  </span>
                )}
              </div>
              <p className="text-xs text-[var(--text-muted)]">Pay-Per-Use AI Post Generator</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <nav className="hidden md:flex items-center gap-5 mr-3 text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">
              <a href="/about.html" className="hover:text-[var(--accent)] transition-colors">About</a>
              <a href="/contact.html" className="hover:text-[var(--accent)] transition-colors">Contact</a>
              <a href="/privacy.html" className="hover:text-[var(--accent)] transition-colors">Privacy</a>
              <a href="/terms.html" className="hover:text-[var(--accent)] transition-colors">Terms</a>
            </nav>

            {/* Theme Toggle Button */}
            <button
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              className="flex items-center justify-center bg-[var(--bg-surface)] hover:bg-[var(--bg-elevated)] text-[var(--text-primary)] border border-[var(--border-subtle)] hover:border-[var(--accent)]/40 p-2.5 rounded-full active:scale-95 transition-all duration-300 shadow-lg shadow-black/20 hover:-translate-y-0.5 cursor-pointer focus-visible:outline-2 focus-visible:outline-[var(--accent)]"
              aria-label="Toggle theme"
            >
              {theme === 'dark' ? (
                <Sun className="w-4 h-4 text-[var(--accent)]" aria-hidden="true" />
              ) : (
                <Moon className="w-4 h-4 text-[var(--accent)]" aria-hidden="true" />
              )}
            </button>

            <button
              disabled={isConnecting}
              onClick={() => {
                if (!isConnected) {
                  const injectedConnector = connectors.find(
                    (c) =>
                      c.id === 'injected' ||
                      c.name.toLowerCase().includes('injected') ||
                      c.id.toLowerCase().includes('meta')
                  )
                  if (injectedConnector) {
                    connect({ connector: injectedConnector })
                  } else if (connectors[0]) {
                    connect({ connector: connectors[0] })
                  } else {
                    setErrorMsg('No injected wallet detected. Please install MetaMask/Rabby or open this page inside the MiniPay wallet app.')
                  }
                }
              }}
              className="flex items-center gap-2 bg-[var(--bg-surface)] hover:bg-[var(--bg-elevated)] active:scale-95 px-4 py-2 rounded-full border border-[var(--border-subtle)] hover:border-[var(--accent)]/40 transition-all duration-300 cursor-pointer shadow-lg shadow-black/40 hover:-translate-y-0.5 focus-visible:outline-2 focus-visible:outline-[var(--accent)] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Wallet className="w-4 h-4 text-[var(--accent)]" aria-hidden="true" />
              <span className="text-sm text-[var(--text-primary)] font-medium">
                {isConnected && address
                  ? `${address.slice(0, 6)}…${address.slice(-4)}`
                  : isConnecting
                  ? 'Connecting...'
                  : 'Connect Wallet'}
              </span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="max-w-6xl w-full mx-auto px-4 md:px-6 py-8 flex-1 flex flex-col justify-start">
        
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Form & Inputs */}
          <div className="lg:col-span-7 flex flex-col gap-6 w-full animate-in">
            <div className="bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-2xl p-6 shadow-xl shadow-black/20 flex flex-col gap-6 relative group overflow-hidden">
              <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-[var(--accent)] via-[var(--accent-2)] to-[var(--accent)] opacity-60" />
              
              <div className="flex flex-col gap-2">
                <div className="flex justify-between items-center">
                  <label htmlFor="prompt-input" className="text-sm font-semibold tracking-wide text-[var(--text-primary)] font-display">
                    Post Idea / Topic
                  </label>
                  <span className="text-xs text-[var(--text-muted)] font-medium">
                    {prompt.length}/200 chars
                  </span>
                </div>
                <textarea
                  id="prompt-input"
                  name="prompt"
                  autoComplete="off"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value.slice(0, 200))}
                  placeholder="e.g. delicious healthy homemade pasta recipe, warm cozy kitchen vibes…"
                  rows={4}
                  className="input-premium rounded-xl p-4 text-sm resize-none focus:ring-2 focus:ring-[var(--accent)] focus:border-transparent outline-none bg-[var(--bg-elevated)] border border-[var(--border-subtle)] text-[var(--text-primary)] w-full"
                />
              </div>

              {/* Tone Selection */}
              <div className="flex flex-col gap-3">
                <label className="text-sm font-semibold tracking-wide text-[var(--text-primary)] font-display">
                  Caption Tone
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
                  {TONES.map((t) => (
                    <button
                      key={t.value}
                      onClick={() => setSelectedTone(t.value)}
                      className={`
                        py-2.5 px-3 text-xs font-medium rounded-xl border transition-all duration-300 active:scale-95 cursor-pointer
                        ${selectedTone === t.value
                          ? 'bg-[var(--accent)] border-[var(--accent)] text-white shadow-lg shadow-[var(--accent-glow)] font-semibold'
                          : 'bg-[var(--bg-surface)] border-[var(--border-subtle)] text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:border-[var(--text-muted)]/40'}
                      `}
                    >
                      {t.name}
                    </button>
                  ))}
                </div>
              </div>

              {/* Price Indicator */}
              <div className="flex items-center gap-3 bg-[var(--bg-elevated)] p-4 rounded-xl border border-[var(--border-subtle)]/60">
                <div className="w-10 h-10 rounded-lg bg-[var(--warning)]/10 flex items-center justify-center text-[var(--warning)]">
                  <Coins className="w-5 h-5" aria-hidden="true" />
                </div>
                <div>
                  <p className="text-[11px] text-[var(--text-muted)] font-medium leading-none mb-1">Fee per generation</p>
                  <p className="text-sm font-semibold text-[var(--text-primary)]">
                    0.02 cUSD <span className="text-[var(--success)] ml-1.5 font-medium text-xs">(~₹1.60 INR)</span>
                  </p>
                </div>
              </div>

              {/* Error messages */}
              {isConnected && chain && chain.id !== TARGET_CHAIN_ID && (
                <div className="bg-[var(--warning)]/10 text-[var(--warning)] border border-[var(--warning)]/20 p-4 rounded-xl text-xs flex flex-col gap-3 animate-in" role="alert" aria-live="assertive">
                  <div className="flex items-start gap-2.5">
                    <AlertCircle className="w-4 h-4 shrink-0 mt-0.5 text-[var(--warning)]" aria-hidden="true" />
                    <span className="leading-relaxed">Wrong network connected. Please switch your wallet to Celo Sepolia to proceed.</span>
                  </div>
                  <button
                    onClick={() => switchChain({ chainId: TARGET_CHAIN_ID })}
                    className="w-full bg-[var(--warning)]/20 hover:bg-[var(--warning)]/30 text-[var(--text-primary)] font-semibold py-2 px-3 rounded-lg border border-[var(--warning)]/30 text-[10px] uppercase tracking-wider active:scale-95 transition-all duration-300 cursor-pointer"
                  >
                    Switch to Celo Sepolia
                  </button>
                </div>
              )}

              {errorMsg && (
                <div className="bg-[var(--error)]/10 text-[var(--error)] border border-[var(--error)]/20 p-4 rounded-xl text-xs flex items-start gap-2.5 animate-in" role="alert" aria-live="assertive">
                  <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" aria-hidden="true" />
                  <span className="leading-relaxed">{errorMsg}</span>
                </div>
              )}

              <button
                disabled={!prompt.trim() || !!loadingStep}
                onClick={handleGenerate}
                className="btn-premium flex items-center justify-center gap-2 rounded-xl py-4 w-full font-bold text-sm disabled:opacity-40 disabled:cursor-not-allowed disabled:transform-none shadow-lg shadow-[var(--accent-glow)] cursor-pointer"
              >
                <Sparkles className="w-4 h-4 animate-pulse" aria-hidden="true" />
                Generate Post
              </button>
            </div>
          </div>

          {/* Right Column: Dynamic Preview / Result Display */}
          <div className="lg:col-span-5 flex flex-col gap-6 w-full animate-in" style={{ animationDelay: '100ms' }}>
            
            {loadingStep ? (
              /* High-End Loading State with Stripe-like step tracker */
              <div className="bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-2xl p-6 shadow-xl flex flex-col gap-6 animate-in min-h-[350px]" role="status" aria-live="polite">
                <div className="flex items-center gap-3 border-b border-[var(--border-subtle)] pb-4">
                  <div className="relative">
                    <div className="w-6 h-6 border-2 border-[var(--accent)]/15 border-t-[var(--accent)] rounded-full animate-spin" />
                  </div>
                  <h2 className="text-sm font-semibold text-[var(--text-primary)] tracking-wide uppercase">Generating Post...</h2>
                </div>
                
                <div className="flex flex-col gap-5 my-2">
                  {getLoadingSteps(loadingStep).map((step) => (
                    <div key={step.id} className="flex items-start gap-3.5">
                      <div className="mt-0.5">
                        {step.status === 'complete' ? (
                          <div className="w-5 h-5 rounded-full bg-[var(--success)]/20 text-[var(--success)] flex items-center justify-center border border-[var(--success)]/30 shadow-[0_0_10px_rgba(74,222,128,0.15)]">
                            <Check className="w-3 h-3" aria-hidden="true" />
                          </div>
                        ) : step.status === 'active' ? (
                          <div className="w-5 h-5 rounded-full bg-[var(--accent)]/20 text-[var(--accent)] flex items-center justify-center border border-[var(--accent)]/30 animate-pulse">
                            <div className="w-2.5 h-2.5 rounded-full bg-[var(--accent)] shadow-[0_0_8px_var(--accent)]" />
                          </div>
                        ) : (
                          <div className="w-5 h-5 rounded-full border border-[var(--border-subtle)] bg-[var(--bg-elevated)]" />
                        )}
                      </div>
                      <div className="flex-1">
                        <p className={`text-xs font-semibold ${step.status === 'pending' ? 'text-[var(--text-faint)]' : 'text-[var(--text-primary)]'}`}>
                          {step.label}
                        </p>
                        <p className={`text-[10px] leading-relaxed mt-0.5 ${step.status === 'pending' ? 'text-[var(--text-faint)]' : 'text-[var(--text-muted)]'}`}>
                          {step.status === 'active' ? loadingStep : step.desc}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : result ? (
              /* Beautiful Glassmorphic Result Card (Visualizing as a real social post) */
              <div className="bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-2xl p-5 shadow-xl animate-in relative overflow-hidden flex flex-col gap-4">
                <div className="absolute top-0 right-0 w-32 h-32 bg-[var(--accent)]/5 rounded-full blur-2xl pointer-events-none" />
                
                <div className="flex justify-between items-center border-b border-[var(--border-subtle)] pb-3.5">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full bg-[var(--success)] shadow-[0_0_8px_rgba(74,222,128,0.4)]" />
                    <span className="text-xs font-semibold text-[var(--accent-2)] tracking-wider uppercase">Generated Post</span>
                  </div>
                  <button
                    onClick={() => handleCopy(`${result.caption}\n\n${result.hashtags.join(' ')}`)}
                    className="flex items-center gap-1.5 text-xs text-[var(--text-muted)] hover:text-[var(--text-primary)] bg-[var(--bg-elevated)] hover:bg-[var(--bg-elevated)]/85 px-3 py-1.5 rounded-lg border border-[var(--border-subtle)] active:scale-95 transition-all duration-200 cursor-pointer"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-[var(--success)]" aria-hidden="true" /> : <Copy className="w-3.5 h-3.5" aria-hidden="true" />}
                    <span className="font-medium">{copied ? 'Copied' : 'Copy Text'}</span>
                  </button>
                </div>

                {/* Social media style preview box */}
                <div className="border border-[var(--border-subtle)] rounded-xl overflow-hidden bg-[var(--bg-elevated)]/60">
                  {/* Mock profile head */}
                  <div className="flex items-center gap-2.5 p-3.5 border-b border-[var(--border-subtle)]/40">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-[var(--accent)] to-[var(--accent-2)] flex items-center justify-center text-white text-[10px] font-bold">
                      ME
                    </div>
                    <div>
                      <p className="text-xs font-bold text-[var(--text-primary)]">Your Social Handle</p>
                      <p className="text-[9px] text-[var(--text-muted)] font-medium">Just now • AI Generated</p>
                    </div>
                  </div>

                  {/* Generated Image Showcase */}
                  {result.imageUrl && (
                    <div className="relative group aspect-video overflow-hidden bg-black flex items-center justify-center">
                      <img
                        src={result.imageUrl}
                        alt="Generated post asset"
                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-between p-3.5">
                        <span className="text-[9px] font-semibold text-white/90 bg-black/40 px-2 py-1 rounded-md backdrop-blur-sm">
                          FLUX-Schnell Model
                        </span>
                        <a
                          href={result.imageUrl}
                          download={`caption-ai-${Date.now()}.png`}
                          className="bg-[var(--accent)] hover:bg-[var(--accent)]/90 text-white p-2 rounded-lg border border-white/10 active:scale-95 transition-all text-[10px] flex items-center gap-1 font-semibold"
                        >
                          <Download className="w-3.5 h-3.5" aria-hidden="true" />
                          Download
                        </a>
                      </div>
                    </div>
                  )}

                  {/* Caption & hashtags text block */}
                  <div className="p-4 flex flex-col gap-3">
                    <p className="text-xs text-[var(--text-primary)] leading-relaxed select-all">
                      {result.caption}
                    </p>
                    
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {result.hashtags.map((tag, idx) => (
                        <span
                          key={idx}
                          onClick={() => handleCopy(tag)}
                          className="text-[10px] font-medium px-2 py-0.5 rounded-md bg-[var(--accent)]/10 text-[var(--accent)] border border-[var(--accent)]/20 cursor-pointer active:scale-95 transition-all hover:bg-[var(--accent)]/20"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                <button
                  onClick={resetGenerator}
                  className="btn-premium flex items-center justify-center gap-2 rounded-xl py-3.5 mt-2 w-full font-bold text-xs cursor-pointer"
                >
                  <RotateCcw className="w-3.5 h-3.5" aria-hidden="true" />
                  Generate Another
                </button>
              </div>
            ) : (
              /* Designed Empty State with stunning post wireframe and shimmer shadow */
              <div className="border border-dashed border-[var(--border-subtle)] rounded-2xl p-6 flex flex-col items-center justify-center text-center min-h-[350px] bg-[var(--bg-surface)]/50 backdrop-blur-sm relative group overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-tr from-[var(--accent)]/5 to-[var(--accent-2)]/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />
                
                <div className="w-full max-w-sm flex flex-col gap-4 opacity-30 group-hover:opacity-50 transition-opacity duration-300">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-[var(--bg-elevated)]" />
                    <div className="flex-1 flex flex-col gap-1.5">
                      <div className="w-24 h-3 rounded-full bg-[var(--bg-elevated)]" />
                      <div className="w-16 h-2 rounded-full bg-[var(--bg-elevated)]" />
                    </div>
                  </div>
                  
                  <div className="flex flex-col gap-2">
                    <div className="w-full h-3 rounded-full bg-[var(--bg-elevated)]" />
                    <div className="w-[85%] h-3 rounded-full bg-[var(--bg-elevated)]" />
                    <div className="w-[50%] h-3 rounded-full bg-[var(--bg-elevated)]" />
                  </div>
                  
                  <div className="aspect-video rounded-xl bg-[var(--bg-elevated)] flex items-center justify-center border border-[var(--border-subtle)] relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full animate-[shimmer_2s_infinite]" />
                    <Sparkles className="w-8 h-8 text-[var(--text-faint)]" aria-hidden="true" />
                  </div>
                </div>

                <div className="absolute z-10 flex flex-col items-center justify-center p-4">
                  <div className="w-12 h-12 rounded-full bg-[var(--accent)]/10 flex items-center justify-center text-[var(--accent)] mb-3 group-hover:scale-110 transition-transform duration-300">
                    <Sparkles className="w-5 h-5 animate-pulse" />
                  </div>
                  <h3 className="text-sm font-semibold text-[var(--text-primary)] mb-1">Live Post Preview</h3>
                  <p className="text-xs text-[var(--text-muted)] max-w-[200px]">
                    Enter a topic and generate a caption to see the live preview here.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* History Accordion - Full Width Bottom Section */}
        {!loadingStep && history.length > 0 && (
          <div className="mt-12 border-t border-[var(--border-subtle)]/60 pt-8 animate-in" style={{ animationDelay: '200ms' }}>
            <div className="flex items-center gap-2.5 mb-5 text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider">
              <History className="w-4 h-4" aria-hidden="true" />
              <span>Recent Generations</span>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {history.map((h, i) => (
                <div
                  key={i}
                  onClick={() => {
                    setResult({ caption: h.caption, hashtags: h.hashtags, imageUrl: h.imageUrl })
                    setPrompt(h.prompt)
                    setSelectedTone(h.tone)
                    // Auto-scroll to preview pane on mobile
                    window.scrollTo({ top: 0, behavior: 'smooth' })
                  }}
                  className="flex justify-between items-start bg-[var(--bg-surface)] p-4 rounded-xl border border-[var(--border-subtle)] hover:border-[var(--accent)]/40 cursor-pointer transition-all duration-300 hover:-translate-y-1 hover:shadow-lg shadow-black/10 group"
                >
                  <div className="overflow-hidden pr-3 flex-1">
                    <p className="text-xs text-[var(--text-primary)] truncate font-semibold mb-1 group-hover:text-[var(--accent)] transition-colors duration-200">{h.prompt}</p>
                    <p className="text-[10px] text-[var(--text-muted)] font-medium">
                      {h.tone} • {new Date(h.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {h.imageUrl && (
                      <div className="w-8 h-8 rounded bg-black overflow-hidden border border-[var(--border-subtle)]">
                        <img src={h.imageUrl} alt="preview" className="w-full h-full object-cover" />
                      </div>
                    )}
                    <span className="text-[10px] font-bold bg-[var(--bg-elevated)] group-hover:bg-[var(--accent)]/15 group-hover:text-[var(--accent)] px-2.5 py-1.5 rounded-lg border border-[var(--border-subtle)] transition-colors duration-200 select-none">
                      Load
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* JSON-LD Structured Data for FAQ SEO */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": FAQ_DATA.map(faq => ({
              "@type": "Question",
              "name": faq.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
              }
            }))
          })}
        </script>

        {/* FAQ Section */}
        <section className="mt-16 border-t border-[var(--border-subtle)]/60 pt-10 pb-6 animate-in" style={{ animationDelay: '250ms' }} id="faq">
          <div className="flex items-center gap-2.5 mb-6 text-xs font-bold text-[var(--text-muted)] uppercase tracking-wider">
            <HelpCircle className="w-4 h-4 text-[var(--accent)]" aria-hidden="true" />
            <span>Frequently Asked Questions</span>
          </div>

          <div className="flex flex-col gap-3.5 max-w-3xl mx-auto">
            {FAQ_DATA.map((faq, idx) => {
              const isOpen = openFaq === idx
              return (
                <div
                  key={idx}
                  className="bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-xl overflow-hidden transition-all duration-300 hover:border-[var(--accent)]/40 hover:-translate-y-0.5 hover:shadow-lg shadow-black/10"
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between p-4 text-left cursor-pointer transition-colors duration-200"
                    aria-expanded={isOpen}
                    id={`faq-btn-${idx}`}
                  >
                    <span className="text-sm font-semibold text-[var(--text-primary)] pr-4">
                      {faq.question}
                    </span>
                    <ChevronDown
                      className={`w-4 h-4 text-[var(--text-muted)] shrink-0 transition-transform duration-300 ${isOpen ? 'rotate-180 text-[var(--accent)]' : ''}`}
                      aria-hidden="true"
                    />
                  </button>
                  <div
                    className={`transition-all duration-300 ease-in-out overflow-hidden ${
                      isOpen ? 'max-h-40 border-t border-[var(--border-subtle)]/40' : 'max-h-0'
                    }`}
                  >
                    <p className="p-4 text-xs leading-relaxed text-[var(--text-muted)]">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              )
            })}
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="w-full bg-[var(--bg-surface)]/40 border-t border-[var(--border-subtle)]/50 py-6 mt-12">
        <div className="max-w-6xl w-full mx-auto px-4 text-center text-xs text-[var(--text-faint)] font-semibold tracking-wide flex flex-col sm:flex-row items-center justify-between gap-3">
          <p>© 2026 CaptionAI • Built for Celo Proof of Ship</p>
          <div className="flex gap-4 flex-wrap justify-center">
            <a href="/about.html" className="hover:text-[var(--accent)] transition-colors">About Us</a>
            <a href="/contact.html" className="hover:text-[var(--accent)] transition-colors">Contact Us</a>
            <a href="/privacy.html" className="hover:text-[var(--accent)] transition-colors">Privacy Policy</a>
            <a href="/terms.html" className="hover:text-[var(--accent)] transition-colors">Terms &amp; Conditions</a>
          </div>
          <p className="flex items-center gap-1.5">
            Network:
            <span className="text-[var(--accent)] bg-[var(--accent)]/10 px-2.5 py-1 rounded-md border border-[var(--accent)]/20 font-bold">
              {chain?.name ? chain.name : 'Celo Sepolia'}
            </span>
          </p>
        </div>
      </footer>
    </div>
  )
}
